# Site settings
title: Ja.Herrera
index_title: Ja.Herrera # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: A bit of me
header-img: img/home-bg.jpg
# email: root@shikherverma.com
copyright_name: Ja.Herrera
description: "CV and blog of Ja.Herrera"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
# url: shikherverma.com #only used in disque comments for now
github_username:  josekron
# facebook_username:  shikherverma1
twitter_username: joseantonio_hp
email_username:  joseantonioherrerap@gmail.com
# used to estimate reading time
wpm: 180

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed]
